apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: microshak
  labels:
    app: microshak
spec:
  selector:
    matchLabels:
      app: microshak
  replicas: 1
  template:
    metadata:
      labels:
        app: microshak
    spec:
      containers:
      - name: microshak
        image: microshak/web:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 5000
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: microshak
spec:
  selector:
    app: microshak
  ports:
  - port: 80
    targetPort: web

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: microshakingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `www.microshak.com`, `microshak.com`) 
    kind: Rule
    services:
    - name: microshak
      port: 80

